// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Run Google gcloud commands in Direktiv",
    "title": "gcloud",
    "version": "1.0",
    "x-direktiv-meta": {
      "categories": [
        "cloud",
        "aws"
      ],
      "container": "direktiv/gcloud",
      "issues": "https://github.com/direktiv-apps/gcloud/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "This function executes alist of commans. It can run gcloud commands but has basic build tools installed as well, e.g. git.\n",
      "maintainer": "[direktiv.io](https://www.direktiv.io)",
      "url": "https://github.com/direktiv-apps/gcloud"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "account",
                "key",
                "project"
              ],
              "properties": {
                "account": {
                  "description": "Service account name",
                  "type": "string",
                  "example": "sa@myproject.iam.gserviceaccount.com"
                },
                "commands": {
                  "description": "List of commands to run. Use ` + "`" + `--format=json` + "`" + ` to get JSON results.",
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "example": "gcloud compute instances list --format=json"
                },
                "continue": {
                  "description": "If set to true all commands are getting executed and errors ignored.",
                  "type": "boolean",
                  "default": false,
                  "example": true
                },
                "key": {
                  "description": "JSON access file (IAM).",
                  "type": "string"
                },
                "project": {
                  "description": "Specifies the project name.",
                  "type": "string",
                  "example": "my-project-234"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Responds with a list of results",
            "schema": {
              "type": "object",
              "additionalProperties": false,
              "example": {
                "greeting": "Hello YourName"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "exec",
              "exec": "bash -c 'echo {{ .Key }} | base64 -d \u003e key.json'"
            },
            {
              "action": "exec",
              "env": [
                "HOME={{ .DirektivDir }}"
              ],
              "exec": "gcloud auth activate-service-account {{ .Account }} --key-file=key.json"
            },
            {
              "action": "foreach",
              "continue": "{{ .Body.Continue }}",
              "env": [
                "HOME={{ .DirektivDir }}",
                "CLOUDSDK_CORE_PROJECT={{ .Body.Project }}"
              ],
              "exec": "{{ .Item }}",
              "loop": ".Commands",
              "silent": true
            }
          ],
          "output": "{\n  \"gcloud\": {{ index . 2 | toJson }}\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: req\n     type: action\n     action:\n       function: gcloud",
            "title": "Basic"
          },
          {
            "content": "- id: req\n     type: action\n     action:\n       function: gcloud",
            "title": "Running Scripts"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: gcloud\n    image: direktiv/gcloud:1.0\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Run Google gcloud commands in Direktiv",
    "title": "gcloud",
    "version": "1.0",
    "x-direktiv-meta": {
      "categories": [
        "cloud",
        "aws"
      ],
      "container": "direktiv/gcloud",
      "issues": "https://github.com/direktiv-apps/gcloud/issues",
      "license": "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)",
      "long-description": "This function executes alist of commans. It can run gcloud commands but has basic build tools installed as well, e.g. git.\n",
      "maintainer": "[direktiv.io](https://www.direktiv.io)",
      "url": "https://github.com/direktiv-apps/gcloud"
    }
  },
  "paths": {
    "/": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "direktiv action id is an UUID. \nFor development it can be set to 'development'\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          },
          {
            "type": "string",
            "description": "direktiv temp dir is the working directory for that request\nFor development it can be set to e.g. '/tmp'\n",
            "name": "Direktiv-TempDir",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "account",
                "key",
                "project"
              ],
              "properties": {
                "account": {
                  "description": "Service account name",
                  "type": "string",
                  "example": "sa@myproject.iam.gserviceaccount.com"
                },
                "commands": {
                  "description": "List of commands to run. Use ` + "`" + `--format=json` + "`" + ` to get JSON results.",
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "example": "gcloud compute instances list --format=json"
                },
                "continue": {
                  "description": "If set to true all commands are getting executed and errors ignored.",
                  "type": "boolean",
                  "default": false,
                  "example": true
                },
                "key": {
                  "description": "JSON access file (IAM).",
                  "type": "string"
                },
                "project": {
                  "description": "Specifies the project name.",
                  "type": "string",
                  "example": "my-project-234"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Responds with a list of results",
            "schema": {
              "type": "object",
              "additionalProperties": false,
              "example": {
                "greeting": "Hello YourName"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            },
            "headers": {
              "Direktiv-ErrorCode": {
                "type": "string"
              },
              "Direktiv-ErrorMessage": {
                "type": "string"
              }
            }
          }
        },
        "x-direktiv": {
          "cmds": [
            {
              "action": "exec",
              "exec": "bash -c 'echo {{ .Key }} | base64 -d \u003e key.json'"
            },
            {
              "action": "exec",
              "env": [
                "HOME={{ .DirektivDir }}"
              ],
              "exec": "gcloud auth activate-service-account {{ .Account }} --key-file=key.json"
            },
            {
              "action": "foreach",
              "continue": "{{ .Body.Continue }}",
              "env": [
                "HOME={{ .DirektivDir }}",
                "CLOUDSDK_CORE_PROJECT={{ .Body.Project }}"
              ],
              "exec": "{{ .Item }}",
              "loop": ".Commands",
              "silent": true
            }
          ],
          "output": "{\n  \"gcloud\": {{ index . 2 | toJson }}\n}\n"
        },
        "x-direktiv-errors": {
          "io.direktiv.command.error": "Command execution failed",
          "io.direktiv.output.error": "Template error for output generation of the service",
          "io.direktiv.ri.error": "Can not create information object from request"
        },
        "x-direktiv-examples": [
          {
            "content": "- id: req\n     type: action\n     action:\n       function: gcloud",
            "title": "Basic"
          },
          {
            "content": "- id: req\n     type: action\n     action:\n       function: gcloud",
            "title": "Running Scripts"
          }
        ],
        "x-direktiv-function": "functions:\n  - id: gcloud\n    image: direktiv/gcloud:1.0\n    type: knative-workflow"
      },
      "delete": {
        "parameters": [
          {
            "type": "string",
            "description": "On cancel Direktiv sends a DELETE request to\nthe action with id in the header\n",
            "name": "Direktiv-ActionID",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "x-direktiv": {
          "cancel": "echo 'cancel {{ .DirektivActionID }}'"
        }
      }
    }
  },
  "definitions": {
    "direktivFile": {
      "type": "object",
      "x-go-type": {
        "import": {
          "package": "github.com/direktiv/apps/go/pkg/apps"
        },
        "type": "DirektivFile"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "errorCode",
        "errorMessage"
      ],
      "properties": {
        "errorCode": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    }
  }
}`))
}
